-- Demo: System Time Functions

USE AdventureWorks2012;

SELECT 'SYSDATETIME' AS STFunction, SYSDATETIME();

SELECT 'SYSDATETIMEOFFSET' AS STFunction, SYSDATETIMEOFFSET();

SELECT 'SYSUTCDATETIME' AS STFunction, SYSUTCDATETIME();

SELECT 'CURRENT_TIMESTAMP' AS STFunction, CURRENT_TIMESTAMP;

SELECT 'GETUTCDATE' AS STFunction, GETUTCDATE();

SELECT 'GETDATE' AS STFunction, GETDATE();

